language: node_js
node_js: stable

cache:
    directories:
        - ./api/node_modules

before_deploy:
    - 'cd api'
    - 'npm run docs:build'

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: docs
    on:
        branch: master
